# =========================================
# CERES RISC-V — Centralized Help System
# =========================================
# Tüm help target'larını tek bir yerden yönet

.PHONY: help help_all help_tests help_sim help_build help_utils

# Ana help (varsayılan)
help:
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(GREEN)                    CERES RISC-V Makefile Help$(RESET)"
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Quick Reference:$(RESET)"
	@echo -e "  help            Show this help message"
	@echo -e "  help_sim        Show simulation targets"
	@echo -e "  help_tests      Show test commands and suites"
	@echo -e "  help_build      Show build and synthesis targets"
	@echo -e "  help_utils      Show utility commands"
	@echo -e "  help_all        Show complete help (all sections)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Most Common Commands:$(RESET)"
	@echo -e "  make verilate         Build Verilator model"
	@echo -e "  make run T=<test>     Run single test"
	@echo -e "  make isa              Run all ISA tests"
	@echo -e "  make cm               Run CoreMark benchmark"
	@echo -e "  make clean            Clean build artifacts"
	@echo -e ""
	@echo -e "$(YELLOW)For detailed help on specific topics, use:$(RESET)"
	@echo -e "  make help_sim     → Simulation and waveform commands"
	@echo -e "  make help_tests   → Test suites and configurations"
	@echo -e "  make help_build   → Build modes and synthesis"
	@echo -e "  make help_utils   → Linting, cleaning, and tools"
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""

# Detaylı simülasyon help'i
help_sim:
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(GREEN)                    Simulation Targets$(RESET)"
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Verilator (Primary Simulator):$(RESET)"
	@echo -e "  verilate        Build Verilator C++ model"
	@echo -e "  verilate-fast   Build only if sources changed"
	@echo -e "  run_verilator   Run Verilator simulation"
	@echo -e "  rebuild-cpp     Rebuild C++ testbench only"
	@echo -e ""
	@echo -e "$(CYAN)▶ ModelSim:$(RESET)"
	@echo -e "  compile         Compile RTL with ModelSim"
	@echo -e "  simulate        Run batch simulation"
	@echo -e "  simulate_gui    Run GUI simulation with waveforms"
	@echo -e ""
	@echo -e "$(CYAN)▶ Icarus Verilog:$(RESET)"
	@echo -e "  iverilog        Compile with Icarus Verilog"
	@echo -e "  run_icarus      Run Icarus simulation"
	@echo -e ""
	@echo -e "$(CYAN)▶ Waveform Viewers:$(RESET)"
	@echo -e "  gtkwave         Open waveform with GTKWave"
	@echo -e "  surfer          Open waveform with Surfer"
	@echo -e "  konata          Open Konata pipeline visualizer"
	@echo -e ""
	@echo -e "$(CYAN)▶ Trace & Debug Options:$(RESET)"
	@echo -e "  LOG_COMMIT=1        Spike-compatible commit trace"
	@echo -e "  LOG_PIPELINE=1      Konata pipeline trace file"
	@echo -e "  LOG_RAM=1           RAM initialization messages"
	@echo -e "  LOG_UART=1          UART TX file logging"
	@echo -e "  LOG_BP=1            Branch predictor statistics"
	@echo -e "  LOG_BP_VERBOSE=1    Per-branch verbose logging"
	@echo -e "  KONATA_TRACER=1     Enable Konata visualizer"
	@echo -e "  TRACE=1             Enable waveform tracing"
	@echo -e "  SIM_FAST=1          Fast mode (disable all logs)"
	@echo -e "  SIM_UART_MONITOR=1  UART monitoring + auto-stop"
	@echo -e "  SIM_COVERAGE=1      Enable coverage collection"
	@echo -e ""
	@echo -e "$(CYAN)▶ Examples:$(RESET)"
	@echo -e "  make verilate LOG_COMMIT=1 TRACE=1"
	@echo -e "  make run_verilator LOG_BP=1 SIM_FAST=1"
	@echo -e "  make simulate_gui"
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""

# Detaylı test help'i
help_tests:
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(GREEN)                    Test Commands$(RESET)"
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Basic Test Commands:$(RESET)"
	@echo -e "  run T=<name>    Run single test with RTL+Spike comparison"
	@echo -e "  quick_test      Run RTL only (skip Spike)"
	@echo -e "  run_batch       Run multiple tests from list"
	@echo -e "  list_tests      List available tests"
	@echo -e ""
	@echo -e "$(CYAN)▶ Test Suites (Standard):$(RESET)"
	@echo -e "  isa             All ISA tests (riscv-tests)"
	@echo -e "  arch            Architecture tests (riscv-arch-test)"
	@echo -e "  imperas         Imperas tests"
	@echo -e "  bench           Benchmarks"
	@echo -e "  csr             CSR tests"
	@echo -e "  all_tests       Run ALL tests"
	@echo -e ""
	@echo -e "$(CYAN)▶ Quick Test Shortcuts:$(RESET)"
	@echo -e "  t T=<name>      Quick ISA test    (e.g., make t T=rv32ui-p-add)"
	@echo -e "  tb T=<name>     Quick benchmark   (e.g., make tb T=dhrystone)"
	@echo -e "  ti T=<name>     Quick Imperas test"
	@echo -e ""
	@echo -e "$(CYAN)▶ Benchmarks:$(RESET)"
	@echo -e "  cm              Build and run CoreMark"
	@echo -e "  cm_run          Quick CoreMark run (skip rebuild)"
	@echo -e "  coremark_help   Show CoreMark detailed help"
	@echo -e "  dhrystone       Build Dhrystone"
	@echo -e "  dhrystone_run   Run Dhrystone"
	@echo -e "  dhrystone_help  Show Dhrystone detailed help"
	@echo -e "  embench         Build Embench-IoT"
	@echo -e "  embench_run     Run Embench benchmarks"
	@echo -e ""
	@echo -e "$(CYAN)▶ Extended Test Suites:$(RESET)"
	@echo -e "  torture         Generate & build torture tests"
	@echo -e "  torture_run     Run torture tests"
	@echo -e "  torture_help    Show torture detailed help"
	@echo -e "  riscv_dv        Build RISCV-DV tests"
	@echo -e "  riscv_dv_run    Run RISCV-DV tests"
	@echo -e "  riscv_dv_help   Show RISCV-DV detailed help"
	@echo -e "  formal          Run formal verification"
	@echo -e ""
	@echo -e "$(CYAN)▶ Test Suite Management:$(RESET)"
	@echo -e "  isa_help        ISA test import help"
	@echo -e "  arch_help       Architecture test help"
	@echo -e "  imperas_help    Imperas test help"
	@echo -e ""
	@echo -e "$(CYAN)▶ Examples:$(RESET)"
	@echo -e "  make run T=rv32ui-p-add LOG_COMMIT=1"
	@echo -e "  make isa LOG_BP=1"
	@echo -e "  make cm SIM_FAST=1 SIM_UART_MONITOR=1"
	@echo -e "  make run_batch TEST_LIST=my_tests.list"
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""

# Build ve synthesis help'i
help_build:
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(GREEN)                    Build & Synthesis$(RESET)"
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Build Modes:$(RESET)"
	@echo -e "  MODE=debug      Full tracing, assertions ON (default)"
	@echo -e "  MODE=release    Optimized build, minimal logging"
	@echo -e "  MODE=test       RISC-V test mode with assertions"
	@echo -e ""
	@echo -e "$(CYAN)▶ Synthesis:$(RESET)"
	@echo -e "  yosys           Run Yosys synthesis"
	@echo -e "  yosys_check     Run Yosys structural checks"
	@echo -e "  yosys_clean     Clean Yosys build artifacts"
	@echo -e "  asic_subrepos   Clone/update ASIC GitHub repos under subrepo/"
	@echo -e "  asic_setup      Pull OpenLane image and check PDK path"
	@echo -e "  asic_prep       Prepare OpenLane source set"
	@echo -e "  asic_run        Run OpenLane full RTL→GDS flow"
	@echo -e "  asic_report     Show latest OpenLane run artifacts"
	@echo -e "  asic_clean      Clean OpenLane runs and prepared sources"
	@echo -e ""
	@echo -e "$(CYAN)▶ Configuration:$(RESET)"
	@echo -e "  TEST_CONFIG=X   Use specific JSON test config"
	@echo -e "  list-configs    List available test configurations"
	@echo -e "  show-config     Show current config values"
	@echo -e "  MAX_CYCLES=N    Set max simulation cycles"
	@echo -e ""
	@echo -e "$(CYAN)▶ Examples:$(RESET)"
	@echo -e "  make verilate MODE=release"
	@echo -e "  make run T=rv32ui-p-add MODE=test MAX_CYCLES=10000"
	@echo -e "  make yosys"
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""

# Utilities help'i
help_utils:
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(GREEN)                    Utility Commands$(RESET)"
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
	@echo -e "$(CYAN)▶ Linting & Verification:$(RESET)"
	@echo -e "  lint            Run Verilator lint check"
	@echo -e "  lint-report     Detailed lint report with stats"
	@echo -e "  lint-width      Check width warnings only"
	@echo -e "  lint-unused     Check unused signals only"
	@echo -e "  lint-loops      Check combinational loops"
	@echo -e "  lint-loops-view View loop diagrams as PDF"
	@echo -e ""
	@echo -e "$(CYAN)▶ Cleaning:$(RESET)"
	@echo -e "  clean           Clean all build directories"
	@echo -e "  clean_verilator Clean Verilator build"
	@echo -e "  clean_modelsim  Clean ModelSim build"
	@echo -e "  clean_tests     Clean test artifacts"
	@echo -e "  clean_logs      Clean simulation logs"
	@echo -e ""
	@echo -e "$(CYAN)▶ Waveform & Visualization:$(RESET)"
	@echo -e "  gtkwave         Open waveform with GTKWave"
	@echo -e "  surfer          Open waveform with Surfer"
	@echo -e "  konata          Open Konata pipeline visualizer"
	@echo -e ""
	@echo -e "$(CYAN)▶ Statistics & Reports:$(RESET)"
	@echo -e "  stats           Show Verilator statistics"
	@echo -e "  verilator_help  Verilator-specific help"
	@echo -e ""
	@echo -e "$(GREEN)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""

# Tüm help'leri göster
help_all: help help_sim help_tests help_build help_utils
	@echo -e "$(YELLOW)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e "$(YELLOW)End of complete help. For specific suite help, use:$(RESET)"
	@echo -e "  make isa_help, arch_help, imperas_help, dhrystone_help,"
	@echo -e "  make torture_help, riscv_dv_help, coremark_help"
	@echo -e "$(YELLOW)━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━$(RESET)"
	@echo -e ""
