# Level RTL file list — one path per line, repo-root relative (rtl/...).
# Makefile SV_SOURCES is built from this file. # and blank lines ignored.
rtl/pkg/level_param.sv
rtl/core/cpu.sv
rtl/core/hazard_unit.sv
rtl/core/bus/wb_interconnect.sv
rtl/core/bus/wb_master_bridge.sv
rtl/core/pmp_pma/pma.sv
rtl/core/stage01_fetch/align_buffer.sv
rtl/core/stage01_fetch/compressed_decoder.sv
rtl/core/stage01_fetch/fetch.sv
rtl/core/stage01_fetch/gshare_bp.sv
rtl/core/stage01_fetch/next_line_prefetcher.sv
rtl/core/stage01_fetch/prefetcher_wrapper.sv
rtl/core/stage01_fetch/ras.sv
rtl/core/stage02_decode/control_unit.sv
rtl/core/stage02_decode/decode.sv
rtl/core/stage02_decode/extend.sv
rtl/core/stage02_decode/reg_file.sv
rtl/core/stage03_execute/alu.sv
rtl/core/stage03_execute/cs_reg_file.sv
rtl/core/stage03_execute/execution.sv
rtl/core/stage03_execute/mul_div/divu_int.sv
rtl/core/stage03_execute/mul_div/divu_pipelined.sv
rtl/core/stage03_execute/mul_div/mul_int.sv
rtl/core/stage03_execute/mul_div/mul_pipelined.sv
rtl/core/stage03_execute/mul_div/wallace32x32/add.sv
rtl/core/stage03_execute/mul_div/wallace32x32/cla.sv
rtl/core/stage03_execute/mul_div/wallace32x32/configure.sv
rtl/core/stage03_execute/mul_div/wallace32x32/dadda.sv
rtl/core/stage03_execute/mul_div/wallace32x32/fa.sv
rtl/core/stage03_execute/mul_div/wallace32x32/ha.sv
rtl/core/stage03_execute/mul_div/wallace32x32/mul.sv
rtl/core/stage03_execute/mul_div/wallace32x32/mutex.sv
rtl/core/stage03_execute/mul_div/wallace32x32/wallace.sv
rtl/core/stage04_memory/cache_logger.sv
rtl/core/stage04_memory/memory.sv
rtl/core/stage04_memory/store_buffer.sv
rtl/core/stage05_writeback/writeback.sv
rtl/core/mmu/cache.sv
rtl/core/mmu/dcache.sv
rtl/core/mmu/dcache_fencei.sv
rtl/core/mmu/icache.sv
rtl/core/mmu/memory_arbiter.sv
rtl/core/mmu/nbmbmp_l2_cache.sv
rtl/util/fifo.sv
rtl/periph/gpio/axi_gpio.sv
rtl/periph/gpio/axi_gpio_bridge.sv
rtl/periph/gpio/gpio.sv
rtl/periph/gpio/xilinx_gpio_wrapper.sv
rtl/periph/plic/plic.sv
rtl/periph/timer/gptimer.sv
rtl/periph/wdt/watchdog.sv
rtl/periph/dma/dma.sv
rtl/periph/pwm/pwm.sv
rtl/periph/vga/vga_char_rom.sv
rtl/periph/vga/vga_clk_gen.sv
rtl/periph/vga/vga_controller.sv
rtl/periph/i2c/i2c_master.sv
rtl/periph/i2c/i2c_slave_sim.sv
rtl/periph/spi/spi_master.sv
rtl/periph/uart/uart.sv
rtl/periph/uart/uart_rx.sv
rtl/periph/uart/uart_tx.sv
rtl/tracer/konata_logger.sv
rtl/ram/dp_bram.sv
rtl/ram/sky130_sram_1kbyte_1rw1r_32x256_8.bb.sv
rtl/ram/sp_bram.sv
rtl/wrapper/level_wrapper.sv
rtl/wrapper/ram_programmer.sv
rtl/wrapper/systessis_wrapper.sv
rtl/wrapper/wb_clint_slave.sv
rtl/wrapper/wb_pbus_slave.sv
rtl/wrapper/wb_ram_slave.sv
rtl/wrapper/wrapper_ram.sv
rtl/wrapper/simpleuart.v
