#!/usr/bin/env python3
# Generate rtl/include-style localparam block from rtl/cfg/<profile>.cfg
# Invoked by Makefile (verilator) and prepare_openlane_sources.sh (ASIC).
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CFG_DIR = ROOT / "rtl" / "cfg"

# All keys that must appear in every profile .cfg
REQUIRED = (
    "WRAPPER_RAM_SIZE_KB",
    "IC_WAY",
    "IC_KB",
    "DC_WAY",
    "DC_KB",
    "DC_MSHR_DEPTH",
    "DC_NUM_BANK",
    "L2_CACHE_SIZE_KB",
    "L2_NUM_WAY",
    "L2_MSHR_DEPTH",
    "L2_NUM_BANKS",
    "PHT_SIZE",
    "BTB_SIZE",
    "GHR_SIZE",
    "IBTC_SIZE",
    "RAS_SIZE",
    "LOOP_SIZE",
    "UART_TX_FIFO_DEPTH",
    "UART_RX_FIFO_DEPTH",
    "ABUFF_SIZE",
    "ABUFF_WAY",
    "BP_LOG_INTERVAL",
    "PREFETCH_TYPE",
    "STRIDE_TABLE_SIZE",
    "STRIDE_BITS",
    "NUM_STREAMS",
    "PREFETCH_DEGREE",
    "SB_DEPTH",
)

_INT_RE = re.compile(r"^-?[0-9]+$")


def _sv_string_literal(profile: str) -> str:
    esc = profile.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{esc}"'


def load_cfg(path: Path) -> dict[str, str]:
    kv: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k = k.strip()
        v = v.strip()
        if k:
            kv[k] = v
    return kv


def validate(kv: dict[str, str], profile: str) -> None:
    missing = [k for k in REQUIRED if k not in kv]
    if missing:
        sys.stderr.write(
            f"{sys.argv[0]}: profile {profile!r} missing keys: {', '.join(missing)}\n"
        )
        sys.exit(1)
    for k in REQUIRED:
        if not _INT_RE.match(kv[k]):
            sys.stderr.write(
                f"{sys.argv[0]}: {profile}.cfg: {k}={kv[k]!r} must be an integer\n"
            )
            sys.exit(1)


def emit_profile_svh(profile: str, kv: dict[str, str]) -> str:
    def i(name: str) -> str:
        return kv[name]

    lines = [
        "// Generated by gen_level_param_profile.py — do not edit",
        "// Source: rtl/cfg/<profile>.cfg",
        "",
        f"  localparam string RTL_CFG_PROFILE_NAME = {_sv_string_literal(profile)};",
        "",
        f"  localparam int WRAPPER_RAM_SIZE_KB = {i('WRAPPER_RAM_SIZE_KB')};",
        "",
        "  localparam int IC_WAY = " + i("IC_WAY") + ";",
        "  localparam int IC_CAPACITY = " + i("IC_KB") + " * 1024 * 8;",
        "  localparam int IC_SIZE = IC_CAPACITY / IC_WAY;",
        "",
        "  localparam int DC_WAY = " + i("DC_WAY") + ";",
        "  localparam int DC_CAPACITY = " + i("DC_KB") + " * 1024 * 8;",
        "  localparam int DC_SIZE = DC_CAPACITY / DC_WAY;",
        "  localparam int DC_MSHR_DEPTH = " + i("DC_MSHR_DEPTH") + ";",
        "  localparam int DC_NUM_BANK = " + i("DC_NUM_BANK") + ";",
        "",
        "  localparam int L2_CACHE_SIZE_KB = " + i("L2_CACHE_SIZE_KB") + ";",
        "  localparam int L2_NUM_WAY = " + i("L2_NUM_WAY") + ";",
        "  localparam int L2_MSHR_DEPTH = " + i("L2_MSHR_DEPTH") + ";",
        "  localparam int L2_NUM_BANKS = " + i("L2_NUM_BANKS") + ";",
        "",
        "  localparam int PHT_SIZE = " + i("PHT_SIZE") + ";",
        "  localparam int BTB_SIZE = " + i("BTB_SIZE") + ";",
        "  localparam int GHR_SIZE = " + i("GHR_SIZE") + ";",
        "  localparam int IBTC_SIZE = " + i("IBTC_SIZE") + ";",
        "  localparam int RAS_SIZE = " + i("RAS_SIZE") + ";",
        "  localparam int LOOP_SIZE = " + i("LOOP_SIZE") + ";",
        "",
        "  localparam int UART_TX_FIFO_DEPTH = " + i("UART_TX_FIFO_DEPTH") + ";",
        "  localparam int UART_RX_FIFO_DEPTH = " + i("UART_RX_FIFO_DEPTH") + ";",
        "",
        "  localparam int ABUFF_SIZE = " + i("ABUFF_SIZE") + ";",
        "  localparam int ABUFF_WAY = " + i("ABUFF_WAY") + ";",
        "  localparam int BP_LOG_INTERVAL = " + i("BP_LOG_INTERVAL") + ";",
        "",
        "  localparam int PREFETCH_TYPE = " + i("PREFETCH_TYPE") + ";",
        "  localparam int STRIDE_TABLE_SIZE = " + i("STRIDE_TABLE_SIZE") + ";",
        "  localparam int STRIDE_BITS = " + i("STRIDE_BITS") + ";",
        "  localparam int NUM_STREAMS = " + i("NUM_STREAMS") + ";",
        "  localparam int PREFETCH_DEGREE = " + i("PREFETCH_DEGREE") + ";",
        "",
        "  localparam int SB_DEPTH = " + i("SB_DEPTH") + ";",
        "  localparam int SB_PTR_W = $clog2(SB_DEPTH);",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "profile",
        help="Profile name (without .cfg), e.g. full_soc, minimal_soc, openlane",
    )
    ap.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output path .svh",
    )
    args = ap.parse_args()

    cfg_path = CFG_DIR / f"{args.profile}.cfg"
    if not cfg_path.is_file():
        sys.stderr.write(f"{sys.argv[0]}: not found: {cfg_path}\n")
        sys.exit(1)

    kv = load_cfg(cfg_path)
    validate(kv, args.profile)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_profile_svh(args.profile, kv), encoding="utf-8")


if __name__ == "__main__":
    main()
