#!/usr/bin/env bash
# Level — test profile .conf → Makefile fragment
# Reads: script/config/tests/default.conf then <name>.conf (later wins).
# Lines: KEY=value  (# comments, blank lines ignored)
#
# - Keys CFG_* are emitted as-is:  CFG_MAX_CYCLES := 10000
# - Shorthand keys map to CFG_* (MAX_CYCLES, COMPARE, SPIKE, SPIKE_ISA, …)
# - Any other KEY= that looks like a Verilog macro (^[A-Z][A-Z0-9_]*$) becomes
#   +define+KEY for truthy values, omitted for falsy, +define+KEY=val otherwise.
# - Optional CFG_SV_DEFINES=+define+A ... is merged with generated defines.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(cd "$SCRIPT_DIR/../config/tests" && pwd)"

usage() {
  sed -n '1,40p' "$0" | sed 's/^# \{0,1\}//'
  echo "Usage: $(basename "$0") <profile> --make"
  echo "       $(basename "$0") --list"
}

is_true() {
  case "${1,,}" in 1|true|yes|on) return 0 ;; *) return 1 ;; esac
}
is_false() {
  case "${1,,}" in 0|false|no|off) return 0 ;; *) return 1 ;; esac
}

list_profiles() {
  echo "Test profiles (.conf in $CONFIG_DIR):"
  shopt -s nullglob
  for f in "$CONFIG_DIR"/*.conf; do
    printf '  %s\n' "$(basename "$f" .conf)"
  done
  shopt -u nullglob
}

# Merge default.conf + <name>.conf into stdout (later file overwrites by re-printing)
merge_files() {
  local name="$1"
  if [[ -f "$CONFIG_DIR/default.conf" ]]; then
    cat "$CONFIG_DIR/default.conf"
  fi
  if [[ "$name" != "default" ]] && [[ -f "$CONFIG_DIR/${name}.conf" ]]; then
    echo ""
    cat "$CONFIG_DIR/${name}.conf"
  fi
}

emit_make() {
  local name="$1"
  declare -A KV
  while IFS= read -r line || [[ -n "${line:-}" ]]; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    [[ "$line" != *"="* ]] && continue
    local k v
    k="${line%%=*}"
    v="${line#*=}"
    k="${k#"${k%%[![:space:]]*}"}"; k="${k%"${k##*[![:space:]]}"}"
    v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
    [[ -z "$k" ]] && continue
    KV["$k"]="$v"
  done < <(merge_files "$name")

  local explicit_sv="${KV[CFG_SV_DEFINES]-}"
  unset 'KV[CFG_SV_DEFINES]'

  local defines=""
  local k v

  echo "# Generated by parse_test_conf.sh — do not edit"
  echo "# Profile: $name"

  for k in "${!KV[@]}"; do
    v="${KV[$k]}"
    if [[ "$k" == CFG_* ]]; then
      printf '%s := %s\n' "$k" "$v"
      continue
    fi
    case "$k" in
      MAX_CYCLES)            printf 'CFG_MAX_CYCLES := %s\n' "$v" ;;
      TIMEOUT)               printf 'CFG_TIMEOUT := %s\n' "$v" ;;
      BUILD_THREADS)         printf 'CFG_BUILD_THREADS := %s\n' "$v" ;;
      SIM_THREADS)           printf 'CFG_SIM_THREADS := %s\n' "$v" ;;
      PARALLEL_JOBS)         printf 'CFG_PARALLEL_JOBS := %s\n' "$v" ;;
      COMPARE)               printf 'CFG_COMPARE := %s\n' "$v" ;;
      SPIKE)                 printf 'CFG_SPIKE := %s\n' "$v" ;;
      NO_ADDR)               printf 'CFG_NO_ADDR := %s\n' "$v" ;;
      MODE)                  printf 'CFG_MODE := %s\n' "$v" ;;
      TRACE)                 printf 'CFG_TRACE := %s\n' "$v" ;;
      TRACE_FORMAT)          printf 'CFG_TRACE_FORMAT := %s\n' "$v" ;;
      TRACE_DEPTH)           printf 'CFG_TRACE_DEPTH := %s\n' "$v" ;;
      OPT_LEVEL)             printf 'CFG_OPT_LEVEL := %s\n' "$v" ;;
      FAST_SIM)              printf 'CFG_FAST_SIM := %s\n' "$v" ;;
      BP_LOG)                printf 'CFG_BP_LOG := %s\n' "$v" ;;
      VERBOSE)               printf 'CFG_VERBOSE := %s\n' "$v" ;;
      SPIKE_ISA)             printf 'CFG_SPIKE_ISA := %s\n' "$v" ;;
      SPIKE_PRIV)            printf 'CFG_SPIKE_PRIV := %s\n' "$v" ;;
      SPIKE_PC)              printf 'CFG_SPIKE_PC := %s\n' "$v" ;;
      SPIKE_TRIGGERS)        printf 'CFG_SPIKE_TRIGGERS := %s\n' "$v" ;;
      SPIKE_PMP_REGIONS)     printf 'CFG_SPIKE_PMP_REGIONS := %s\n' "$v" ;;
      SPIKE_PMP_GRANULARITY) printf 'CFG_SPIKE_PMP_GRANULARITY := %s\n' "$v" ;;
      SPIKE_MISALIGNED)      printf 'CFG_SPIKE_MISALIGNED := %s\n' "$v" ;;
      SPIKE_LOG_COMMITS)     printf 'CFG_SPIKE_LOG_COMMITS := %s\n' "$v" ;;
      SPIKE_ENABLED)       printf 'CFG_SPIKE_ENABLED := %s\n' "$v" ;;
      TEST_LIST)
        printf 'CFG_TEST_LIST := $(ROOT_DIR)/%s\n' "$v"
        ;;
      *)
        if [[ "$k" =~ ^[A-Z][A-Z0-9_]*$ ]]; then
          if is_true "$v"; then
            defines+=" +define+${k}"
          elif is_false "$v"; then
            :
          else
            defines+=" +define+${k}=${v}"
          fi
        else
          printf '# Ignored unknown key: %s\n' "$k" >&2
        fi
        ;;
    esac
  done

  defines="${explicit_sv:-}${defines}"
  defines="${defines#"${defines%%[![:space:]]*}"}"
  if [[ -n "${defines// }" ]]; then
    printf 'CFG_SV_DEFINES := %s\n' "$defines"
  fi
}

main() {
  case "${1:-}" in
    --help|-h) usage; exit 0 ;;
    --list|-l) list_profiles; exit 0 ;;
    "") usage; exit 1 ;;
  esac
  local name="$1"
  shift
  case "${1:-}" in
    --make|-m) emit_make "$name" ;;
    *)
      echo "Use: $0 <profile> --make   (other modes removed; use .conf files)" >&2
      exit 1
      ;;
  esac
}

main "$@"
