#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DESIGN_DIR="${ROOT_DIR}/asic/openlane/designs/ceres_wrapper"
SRC_DIR="${DESIGN_DIR}/src"
INC_DIR="${SRC_DIR}/include"
MANIFEST="${DESIGN_DIR}/sources_manifest.txt"
SV2V_IMAGE="${SV2V_IMAGE:-davidsiaw/sv2v:latest}"
SV2V_OUT="${SRC_DIR}/ceres_wrapper_sv2v.v"

echo "[openlane:prep] Root      : ${ROOT_DIR}"
echo "[openlane:prep] Design    : ${DESIGN_DIR}"

rm -rf "${SRC_DIR}"
mkdir -p "${SRC_DIR}" "${INC_DIR}"

copy_glob() {
    local pattern="$1"
    for file in ${pattern}; do
        [[ -f "${file}" ]] || continue
        cp -f "${file}" "${SRC_DIR}/"
    done
}

copy_glob "${ROOT_DIR}/rtl/pkg/ceres_param.sv"
copy_glob "${ROOT_DIR}/rtl/core/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/bus/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/pmp_pma/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage01_fetch/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage02_decode/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage03_execute/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage03_execute/mul_div/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage03_execute/mul_div/wallace8x8/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage03_execute/mul_div/wallace32x32/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage04_memory/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/stage05_writeback/*.sv"
copy_glob "${ROOT_DIR}/rtl/core/mmu/*.sv"
copy_glob "${ROOT_DIR}/rtl/util/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/gpio/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/plic/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/timer/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/wdt/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/dma/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/pwm/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/vga/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/i2c/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/spi/*.sv"
copy_glob "${ROOT_DIR}/rtl/periph/uart/*.sv"
copy_glob "${ROOT_DIR}/rtl/ram/*.sv"
copy_glob "${ROOT_DIR}/rtl/wrapper/*.sv"
copy_glob "${ROOT_DIR}/rtl/wrapper/*.v"

# FPGA-only / Vivado-only wrappers should not enter ASIC flow
rm -f "${SRC_DIR}/xilinx_gpio_wrapper.sv"
rm -f "${SRC_DIR}/systessis_wrapper.sv"

# Simulation-only modules should not enter ASIC synthesis/lint flow
find "${SRC_DIR}" -maxdepth 1 -type f -name '*_sim.sv' -delete

cp -f "${ROOT_DIR}/rtl/include"/*.svh "${INC_DIR}/"
cp -f "${ROOT_DIR}/rtl/include"/*.svh "${SRC_DIR}/"

sv2v_convert() {
    local sv2v_def_args=()
    local sv2v_tmp_out="${SV2V_OUT}.sv2v_tmp.v"
    local d
    for d in SYNTHESIS MINIMAL_SOC CERES_OPENLANE; do
        sv2v_def_args+=("-D" "${d}")
    done

    mapfile -t sv_files < <(find "${SRC_DIR}" -maxdepth 1 -type f \( -name '*.sv' -o -name '*.v' \) | sort)
    if [[ ${#sv_files[@]} -eq 0 ]]; then
        echo "[openlane:prep] WARNING: sv2v için kaynak dosya bulunamadı"
        return 1
    fi

    if ! command -v docker >/dev/null 2>&1; then
        echo "[openlane:prep] WARNING: docker bulunamadı, sv2v adımı atlanıyor"
        return 1
    fi

    find "${SRC_DIR}" -maxdepth 1 -type f \( -name '*.sv' -o -name '*.v' \) \
        -exec perl -i -pe 's/[^\x00-\x7F]/ /g' {} +

    echo "[openlane:prep] sv2v conversion: ${SV2V_IMAGE}"
    rm -f "${SV2V_OUT}" "${sv2v_tmp_out}"
    if docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v "${SRC_DIR}:${SRC_DIR}" \
        -w "${SRC_DIR}" \
        "${SV2V_IMAGE}" \
        sv2v -I "${SRC_DIR}" "${sv2v_def_args[@]}" --top ceres_wrapper --write "${sv2v_tmp_out}" "${sv_files[@]}"; then
        # -----------------------------------------------------------
        # Post-process: sv2v generates struct-type parameters with
        # default value 0.  Yosys evaluates module bodies with these
        # defaults *before* parameter override, and OpenLane's
        # check_out_of_bound treats the resulting "Range select out
        # of bounds" warnings as fatal errors.
        # Fix: replace zero defaults with the actual package values.
        # -----------------------------------------------------------
        echo "[openlane:prep] sv2v post-process: fixing struct-type parameter defaults"
        sed -i \
            -e 's/\(parameter.*_t_ceres_param_XLEN\s*=\s*\)0;/\132;/g' \
            -e 's/\(parameter.*_t_ceres_param_BLK_SIZE\s*=\s*\)0;/\1128;/g' \
            "${sv2v_tmp_out}"

        mv -f "${sv2v_tmp_out}" "${SV2V_OUT}"
    else
        rm -f "${sv2v_tmp_out}" "${SV2V_OUT}"
        return 1
    fi
}

sv2v_convert || true

{
    echo "# Auto-generated by prepare_openlane_sources.sh"
    echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    if [[ -f "${SV2V_OUT}" ]]; then
        echo "${SV2V_OUT}"
    else
        find "${SRC_DIR}" -maxdepth 1 \( -name '*.sv' -o -name '*.v' \) -type f | sort
    fi
} > "${MANIFEST}"

echo "[openlane:prep] Copied RTL: $(find "${SRC_DIR}" -maxdepth 1 \( -name '*.sv' -o -name '*.v' \) -type f | wc -l) files"
echo "[openlane:prep] Include   : $(find "${INC_DIR}" -maxdepth 1 -name '*.svh' -type f | wc -l) files"
echo "[openlane:prep] Manifest  : ${MANIFEST}"
